# Generated by Django 2.2.1 on 2019-06-14 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField(default=0)),
                ('walls', models.IntegerField(default=0)),
                ('ceiling', models.IntegerField(default=0)),
                ('tiles', models.IntegerField(default=0)),
                ('addons', models.IntegerField(default=0)),
                ('basic_sum', models.IntegerField(default=0)),
                ('labor', models.IntegerField(default=0)),
                ('total_sum', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('price', models.FloatField(default=0)),
                ('type', models.IntegerField(choices=[(1, 'Armature'), (2, 'Tiles'), (3, 'Paint'), (4, 'Floor'), (5, 'Other')])),
            ],
        ),
        migrations.CreateModel(
            name='Renovation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=128, null=True)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('type', models.IntegerField(choices=[(1, 'Normal'), (2, 'Bathroom')])),
                ('width', models.FloatField(default=0)),
                ('length', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('tiles_height', models.FloatField(blank=True, default=0, null=True)),
                ('cost', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='renovations.Cost')),
                ('product', models.ManyToManyField(blank=True, to='renovations.Product')),
                ('renovation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='renovations.Renovation')),
            ],
        ),
    ]
