# Generated by Django 2.2.1 on 2019-05-28 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('renovations', '0004_auto_20190528_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='renovation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='renovations.Renovation'),
        ),
        migrations.AlterField(
            model_name='room',
            name='tiles_height',
            field=models.IntegerField(blank=True),
        ),
    ]
