# Generated by Django 2.2.1 on 2019-05-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renovations', '0005_auto_20190528_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='room',
        ),
        migrations.AddField(
            model_name='room',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='renovations.Product'),
        ),
    ]
