# Generated by Django 2.2.1 on 2019-06-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renovations', '0006_auto_20190530_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='product',
            field=models.ManyToManyField(blank=True, to='renovations.Product'),
        ),
    ]
