# Generated by Django 2.2.1 on 2019-06-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renovations', '0007_auto_20190603_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='length',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='tiles_height',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='width',
            field=models.FloatField(),
        ),
    ]
