# Generated by Django 2.2.1 on 2019-06-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renovations', '0008_auto_20190603_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='renovation',
            name='address',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.IntegerField(choices=[(1, 'Armature'), (2, 'Tiles'), (3, 'Paint'), (4, 'Floor'), (5, 'Other')]),
        ),
        migrations.AlterField(
            model_name='renovation',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
