# Generated by Django 2.2.1 on 2019-06-10 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('renovations', '0009_auto_20190606_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField()),
                ('walls', models.IntegerField()),
                ('ceiling', models.IntegerField()),
                ('tiles', models.IntegerField()),
                ('addons', models.IntegerField()),
                ('basic_sum', models.IntegerField()),
                ('labor', models.IntegerField()),
                ('total_sum', models.IntegerField()),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='renovations.Room')),
            ],
        ),
    ]
