# Generated by Django 2.2.1 on 2019-06-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renovations', '0010_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='addons',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cost',
            name='basic_sum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cost',
            name='ceiling',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cost',
            name='floor',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cost',
            name='labor',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cost',
            name='tiles',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cost',
            name='total_sum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cost',
            name='walls',
            field=models.IntegerField(default=0),
        ),
    ]
